name: Martina Hanáková, Personal website
markdown: kramdown
collections:
  interests:
    output: true
    permalink: /interests/:title
collections:
  projects:
    output: true
    permalink: /projects/:title
plugins:
  - jemoji
