name: Martina Hanáková, Personal website
markdown: kramdown
collections:
  interests:
    output: true
    permalink: /interests/:title/
  projects:
    output: true
    permalink: /projects/:title/
plugins:
  - jemoji
  - jekyll-feed
